project_id = "ataqwmyrqppdjujgovok"

[functions.get-interview-session]
verify_jwt = false

[functions.interview-chat]
verify_jwt = false

[functions.score-interview]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
